apiVersion: batch/v1
kind: CronJob
metadata:
    name: sunjobs
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: sunjobs
        spec:
          restartPolicy: OnFailure
          containers:
          - image: quay.io/kennedn/sunjobs
            name: sunjobs
            workingDir: /usr/src/app
            command: ["python"]
            args: ["-u", "sunjobs.py"]
            volumeMounts:
            - name: sunjobs-config-volume
              mountPath:  /usr/src/app/variables.py
              subPath: variables.py
          volumes:
          - name: sunjobs-config-volume
            configMap:
              defaultMode: 420
              name: sunjobs-config

